# Generated by Django 4.2.5 on 2023-09-30 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='Место привычки')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время привычки')),
                ('action', models.CharField(max_length=250, verbose_name='Действие привычки')),
                ('is_nice_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveIntegerField(default=1, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=250, null=True, verbose_name='Награда')),
                ('time_to_complete', models.IntegerField(blank=True, null=True, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('link_nice_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cоздатель привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
